### ISSUE TITLE
Using PacketSendEvent from packetevents makes the frame go around the next tick rather than the current packet/tick.

### ISSUE THREAD

**Issue by y2526** [ThomasOM/Pledge#6]
Hello,

When you use `pledge.getOrCreateFrame()` inside the PacketSendEvent on packetevents 2.0 (or probably any buffer-based packet system) the frame won't wrap around the current packet but only around the next tick's packets. 

Here I used getOrCreateFrame() on the PlayerPosLook packet. That's the clientside log of incoming packets:
![grafik](https://user-images.githubusercontent.com/112286529/215356752-0c349ec7-9e8d-4415-8bb1-c85041903766.png)

Looks like since Pledge's outbound handler comes before packetevent's encoder in the outbound netty pipeline, Pledge will queue the packets (aka cancel the write calls) and wait until the flush call. Then FIRST it checks if there has been any frames in the current tick, adds the frame's packets if there already is a frame and only then passes the write calls on to the next handlers, like packetevents, which means that when packetevents handler gets called for the packet Pledge already thinks this tick/packet doesn't have a frame since it hasnt even been created yet.

Pipeline:
![grafik](https://user-images.githubusercontent.com/112286529/215356926-a9f85483-1769-45e6-be0e-bfd10c8627ec.png)

In pledge's PacketFrameOutboundHandler:
![grafik](https://user-images.githubusercontent.com/112286529/215356969-602e2320-aca6-4e33-bcf7-fb6493e6a7b7.png)

I made a temporary fix for this which involves having Pledge's outbound handler sit after any packet system by adding it after the compress handler rather than the encoder. Since now pledge has to send buffers rather than packets I also had to change the PacketFactory to create a buffer rather than a packet. Idk if there's a better solution, this seems to work but I haven't tested it very much.
(top: PlayerHandler, bottom: TransactionPacketProvider, ping'd need the same)
![grafik](https://user-images.githubusercontent.com/112286529/215357228-66af589f-c4ff-4fa8-aa0f-7d57f96174e5.png)

I haven't tried other packet systems yet but my guess is that stuff like ProtocolLib 5 has similar problems since it's also buffer-based and therefore comes after pledge's handlers.

**Comment by ThomasOM** [comment]
I can add extra support for anything injecting after the encoder step, will mention the commit in your issue once it's done

**Comment by ThomasOM** [comment]
Fixed in https://github.com/ThomasOM/Pledge/commit/f4651d8394e3acaa892c99ec120c5cc9f03b9576
You will see the transactions in the listener, but you can just ignore them.
The order of the transactions might look wrong but it is reordered once it reaches the queue handler.

**Comment by y2526** [comment]
Hey, sadly there's still the same problem with the packet. For one, I think you ment to set the queue handler's state to QUEUE_FIRST and QUEUE_LAST for the frame packets at https://github.com/ThomasOM/Pledge/blob/68e68b21d4cfe808fd3e66ee413f4c70dfb051b7/src/main/java/dev/thomazz/pledge/network/handler/PacketFrameOutboundHandler.java#L51, right?

Also, packetevent's encoder is still added before the outbound_queue handler :/
![grafik](https://user-images.githubusercontent.com/112286529/215573827-cb6fd0e7-14ea-4335-9c20-5dd83ff1a4d2.png)

since packetevents handler already exists when pledge tries to add the queue handler before the encoder, it just places the queue_handler between encoder and packetevents_encoder.

**Comment by y2526** [comment]
I guess adding the queue handler after the compress handler instead of before the encoder might fix the problem, it's just a bit hacky and there might be problems if other plugins do other crazy stuff with the pipeline..

**Comment by ThomasOM** [comment]
Yeah i can do this, it will work

**Comment by ThomasOM** [comment]
See https://github.com/ThomasOM/Pledge/commit/ab2c77cd0034a04002e7b6918f2ba4db08645eb5

**Comment by y2526** [comment]
Hello,

seems to work for now. 
Just in case you really care about packetevents not seeing the transaction packets you might be able to use something similar to this: https://github.com/retrooper/packetevents/blob/7ce167157a5e27f3a5054a667f3c56b2ddc88cfb/spigot/src/main/java/io/github/retrooper/packetevents/manager/protocol/ProtocolManagerImpl.java#L63

**Comment by y2526** [comment]
just gonna summarize the discord stuff:
there are random errors where the frame comes after the packet again
they're caused by keep alive packets flushing the packet queue when they're not supposed to. 
Fix is to change this.flush() to super.flush() in https://github.com/ThomasOM/Pledge/blob/ab2c77cd0034a04002e7b6918f2ba4db08645eb5/src/main/java/dev/thomazz/pledge/network/handler/PacketFrameOutboundQueueHandler.java#L31

**Comment by ThomasOM** [comment]
Yup already fixed
